Update screwdriver.yaml

diff --git a/screwdriver.yaml b/screwdriver.yaml
--- a/screwdriver.yaml
+++ b/screwdriver.yaml
@@ -15,7 +15,7 @@ jobs:
           yum install -y wget git make gcc gcc-c++ jq bzip2
 
           # get skopeo
-          wget -q -O skopeo-${SKOPEO_VERSION}.tar.gz https://github.com/containers/skopeo/releases/download/v${SKOPEO_VERSION}/skopeo-${SKOPEO_VERSION}.tar.gz
+          wget -q -O skopeo-${SKOPEO_VERSION}.tar.gz https://github.com/containers/skopeo/archive/refs/tags/v${SKOPEO_VERSION}.tar.gz
           tar -C . -oxzf skopeo-${SKOPEO_VERSION}.tar.gz
           cd skopeo-${ZSTD_VERSION}
           
@@ -61,23 +61,38 @@ jobs:
     environment:
       ZSTD_PACKAGE: zstd
       ZSTD_VERSION: 1.5.6
+      MUSL_VERSION: 1.2.4
     steps:
       - make: |
           yum install -y epel-release
-          yum install -y zlib-devel wget make gcc gcc-c++ lz4-devel xz-devel glibc-static
-          dnf groupinstall -y "Development Tools"
+          yum install -y wget make gcc gcc-c++
           
+          # Step 1: Install musl from source
+          wget https://musl.libc.org/releases/musl-${MUSL_VERSION}.tar.gz
+          tar -xzf musl-${MUSL_VERSION}.tar.gz
+          cd musl-${MUSL_VERSION}
+          
+          # Configure and install musl with static linking
+          ./configure --prefix=/usr/local/musl
+          make
+          make install
+          cd ..
+          export PATH=/usr/local/musl/bin:$PATH
+
+          # Verify musl installation
+          if ! command -v musl-gcc &> /dev/null; then
+              echo "musl installation failed."
+              exit 1
+          fi
+
           # get ztsd
           wget -q -O zstd-${ZSTD_VERSION}.tar.gz https://github.com/facebook/zstd/releases/download/v${ZSTD_VERSION}/zstd-${ZSTD_VERSION}.tar.gz
           tar -C . -oxzf zstd-${ZSTD_VERSION}.tar.gz
           cd zstd-${ZSTD_VERSION}
 
           # build
-          make lib-release
+          export CC=musl-gcc 
           make CFLAGS="-static -O2" LDFLAGS="-static"
-          # check build
-          ls lib/libzstd.so*
-          ldd lib/libzstd.so
 
           cd programs
           chmod +x ./${ZSTD_PACKAGE}
